spring:
  profiles:
    include: oauth
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
#  mvc:
#    static-path-pattern: /static/**
#  resources:
#    static-locations: classpath:/static/
#    add-mappings: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
