spring:
  jpa:
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#      dialect.storage_engine: innodb
  h2:
    console:
      enabled: true
#datasource:
#  hikari:
#    jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL